src/Entity/Document.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\DocumentRepository;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 * @ORM\InheritanceType("JOINED")
 * @Gedmo\Loggable
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\ManyToOne(targetEntity=Group::class, inversedBy="documents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $mainGroup;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Versioned
     */
    private $share;

    /**
     * @Gedmo\Versioned
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity=Group::class, inversedBy="allowedDocuments")
     */
    private $allowedGroups;

    /**
     * @Gedmo\Versioned
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $allowShare = false;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="document")
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean", options={"default":"0"})
     * @Gedmo\Versioned
     */
    private $archive = false;

    /**
     * True if legal Access is needed
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $needLegalAccess = false;

    /**
     * True if medical Access is needed
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $needMedicalAccess = false;

    /**
     * True if Group Administration Access is needed
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $needGroupAdministration = false;

    /**
     * True if document is public to all groups who have "gang" access
     * @ORM\Column(type="boolean", options={"default":"0"})
     */
    private $isPublic = false;

    /**
     * @ORM\ManyToMany(targetEntity=Folder::class, mappedBy="documents")
     */
    private $folders;

    /**
     * @ORM\ManyToMany(targetEntity=SubGroup::class, inversedBy="documents")
     */
    private $allowedSubGroups;



    public function __construct(User $user)
    {
        $this->allowedGroups = new ArrayCollection();
        $this->share = uniqid();

        $this->setCreator($user);
        $this->setMainGroup($user->getMainGroup());
        $this->addAllowedGroup($this->getMainGroup());

        $this->comments = new ArrayCollection();
        $this->folders = new ArrayCollection();
        $this->allowedSubGroups = new ArrayCollection();
    }

    public function getClass(): ?string
    {
        return get_class($this);
    }

    public function getClassShort(): ?string
    {
        if ($pos = strrpos($this->getClass(), '\\')) {
            return substr($this->getClass(), $pos + 1);
        }
        return $pos;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getMainGroup(): ?Group
    {
        return $this->mainGroup;
    }

    public function setMainGroup(?Group $mainGroup): self
    {
        $this->mainGroup = $mainGroup;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getShare(): ?string
    {
        return $this->share;
    }

    public function setShare(string $share): self
    {
        $this->share = $share;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Group[]
     */
    public function getAllowedGroups(): Collection
    {
        if (!$this->allowedGroups->contains($this->getMainGroup())) {
            $this->allowedGroups[] = $this->getMainGroup();
        }
        return $this->allowedGroups;
    }

    public function addAllowedGroup(Group $allowedGroup): self
    {
        if (!$this->allowedGroups->contains($allowedGroup)) {
            $this->allowedGroups[] = $allowedGroup;
        }

        return $this;
    }

    public function removeAllowedGroup(Group $allowedGroup): self
    {
        $this->allowedGroups->removeElement($allowedGroup);

        return $this;
    }

    public function getAllowShare(): ?bool
    {
        return $this->allowShare;
    }

    public function setAllowShare(bool $allowShare): self
    {
        $this->allowShare = $allowShare;

        return $this;
    }


    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setDocument($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getDocument() === $this) {
                $comment->setDocument(null);
            }
        }

        return $this;
    }

    public function getArchive(): ?bool
    {
        return $this->archive;
    }

    public function setArchive(bool $archive): self
    {
        $this->archive = $archive;

        return $this;
    }

    public function getNeedLegalAccess(): ?bool
    {
        return $this->needLegalAccess;
    }

    public function setNeedLegalAccess(bool $needLegalAccess): self
    {
        $this->needLegalAccess = $needLegalAccess;

        return $this;
    }

    public function getNeedMedicalAccess(): ?bool
    {
        return $this->needMedicalAccess;
    }

    public function setNeedMedicalAccess(bool $needMedicalAccess): self
    {
        $this->needMedicalAccess = $needMedicalAccess;

        return $this;
    }

    public function getNeedGroupAdministration(): ?bool
    {
        return $this->needGroupAdministration;
    }

    public function setNeedGroupAdministration(bool $needGroupAdministration): self
    {
        $this->needGroupAdministration = $needGroupAdministration;

        return $this;
    }

    public function getIsPublic(): ?bool
    {
        return $this->isPublic;
    }

    public function setIsPublic(bool $isPublic): self
    {
        $this->isPublic = $isPublic;

        return $this;
    }

    /**
     * @return Collection|Folder[]
     */
    public function getFolders(): Collection
    {
        return $this->folders;
    }

    public function addFolder(Folder $folder): self
    {
        if (!$this->folders->contains($folder)) {
            $this->folders[] = $folder;
            $folder->addDocument($this);
        }

        return $this;
    }

    public function removeFolder(Folder $folder): self
    {
        if ($this->folders->removeElement($folder)) {
            $folder->removeDocument($this);
        }

        return $this;
    }

    /**
     * @return Collection|SubGroup[]
     */
    public function getAllowedSubGroups(): Collection
    {
        return $this->allowedSubGroups;
    }

    public function addAllowedSubGroup(SubGroup $allowedSubGroup): self
    {
        if (!$this->allowedSubGroups->contains($allowedSubGroup)) {
            $this->allowedSubGroups[] = $allowedSubGroup;
        }

        return $this;
    }

    public function removeAllowedSubGroup(SubGroup $allowedSubGroup): self
    {
        $this->allowedSubGroups->removeElement($allowedSubGroup);

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use App\Form\Type\AllowedGroupsType;
use Symfony\Component\Form\AbstractType;
use App\Form\Type\UserGroupSubGroupsType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class DocumentType extends AbstractType
{
    private TokenStorageInterface $TokenStorage;

    public function __construct(TokenStorageInterface $TokenStorage)
    {
        $this->TokenStorage = $TokenStorage;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /**
         * @var Document $Document
         */
        $Document = $builder->getData();

        /**
         * @var User $User
         */
        $User = $this->TokenStorage->getToken()->getUser();

        $builder
        ->add('title', null, [
            'label' => 'form_label_title',
            'priority' => 999
        ]);

        if (!$Document->getIsPublic()) {
            if ($Document->getMainGroup() == $User->getMainGroup()) {
                $builder
                    ->add(
                        'allowedGroups',
                        AllowedGroupsType::class,
                        [
                            'priority' => -900,
                        ]
                    )
                    ->add(
                        'allowedSubGroups',
                        UserGroupSubGroupsType::class,
                        [
                            'priority' => -900
                        ]
                    );
            }
        }







        $builder
        ->add(
            'allowShare',
            null,
            [
                'priority' => -900,
                'label' => 'form_label_allowShare'
            ]
        )
        ->add('submit', SubmitType::class, [
            'label' => 'form_button_submit',
            'priority' => -900,
            'attr' => ['class' => 'btn-primary'],
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }
}

templates/document/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ "title_creation"|trans }} {{ "of"|trans }}  {{ ('documentType_' ~ type|capitalize)|trans }}
{% endblock %}

{% block body %}
<div class="row">
  <div class="col-lg-8 p-3 py-md-2">    
    {{ form(form) }}
  </div>

  <div class="col-md-4">
    {% if document.directory is defined and document.directory is not null %}
    <h3>{% trans %}title_directory_linked{% endtrans %}</h3><hr>
      {% include '_cells/directoryCard.html.twig' with {'directory': document.directory} %}          
    {% endif %}

    {% if document.user is defined and document.user is not null %}
    <h3>{% trans %}title_user_linked{% endtrans %}</h3><hr>
      {% include '_cells/userInformations.html.twig' with {'user': document.user} %}         
    {% endif %}
  </div>
</div>
{% endblock %}

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}title_edition{% endtrans%} "{{ document.title }}"{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-lg-8">
      {{ form(form) }}
    </div>
    <div class="col-lg-4">
      {% if document.directory is defined and document.directory is not null %}
      <h3>{% trans %}title_directory_linked{% endtrans %}</h3><hr>
      {% include '_cells/directoryCard.html.twig' with {'directory': document.directory} %}          
      {% endif %}

      {% if document.user is defined and document.user is not null %}
      <h3>{% trans %}title_user_linked{% endtrans %}</h3><hr>
        {% include '_cells/userInformations.html.twig' with {'user': document.user} %}         
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/document/history.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ('documentType_' ~ document.classShort)|trans }}: {{ document.getTitle }} - {% trans %}title_history{% endtrans %}{% endblock %}
{% block subtitle %}#{{ document.id }}: {{ document.getTitle }} -  {% trans %}title_history{% endtrans %} {% endblock %}

{% block body %}
<div class="row">
    <div class="col">
        {% include '_cells/historyDisplay.html.twig' with {'history': history, notype: true} %}
    </div>
</div>
{% endblock %}

templates/document/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ('documentType_' ~ type)|trans }}{% if archive %} | {% trans %}title_archives{% endtrans %}{% endif %}{% endblock %}
{% block subtitle %}
  {{ ('documentType_' ~ type)|trans }} {% if archive %} | {% trans %}title_archives{% endtrans %}{% else %}
  {% if documentTypeEntity.directory is not defined and documentTypeEntity.user is not defined %}
    {% if app.user.hasPermission(type ~ '_create')  %}
    <a href="{{ path('document_create', {type: type}) }}"><span class="badge rounded-pill bg-success"><i class="fa fa-plus"></i> {% trans %}button_create{% endtrans %}</span></a>{% endif %}
    {% endif %}
  {% endif %}
{% endblock %}

{% block body %}
  <div class="row">    
        <div class="col-12 col-md-5">{{form(searchForm)}}</div>
        <div class="col-12 col-md-3">
          {% if archive %}
          <a href="{{ path('document_list', {type: type}) }}" class="btn btn-info">{% trans %}button_go_to_not_archived{% endtrans %}</a>
          {% else %}
            <a href="{{ path('document_list_archives', {type: type}) }}" class="btn btn-primary">{% trans %}button_go_to_archived{% endtrans %}</a>
          {% endif %}
        </div>         
  </div>
  <div class="row">
    <div class="col-lg-8"><hr><p>{{ 'title_count'|trans }}: {{ count }}</p>
      {% include '_cells/documentTable.html.twig' with {'documents': pagination, 'notype': true } %}
    </div>

    {% if directory is defined and directory is not null %}
    <div class="col-lg-4">
      <h3>{% trans %}title_document_linked_to_directory{% endtrans %}:</h3>
      <hr>
      {% include '_cells/directoryCard.html.twig' with {'directory': directory} %} 
    </div>
    {% endif %}
    
  </div>
  <div class="row">
    {{ knp_pagination_render(pagination) }}
  </div>
{% endblock %}

templates/document/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ('documentType_' ~ document.classShort)|trans }}: {{ document.getTitle }}{% endblock %}
{% block subtitle %}#{{ document.id }}: {{ document.getTitle }} {% endblock %}

{% block body %}
{% set groupLogo = 'img/nologo.png' %}
{% if document.mainGroup %}
  {% if document.mainGroup.imageSize != 0 %}
    {% set groupLogo = 'uploads/groups/' ~ document.mainGroup.imageName %}
  {% endif %}
{% endif %}
<div class="row p-2">
  <div class="col-lg-8 col-xs-12">
    {% if document.archive %}
    <div class="card prod-p-card bg-primary background-pattern-white">
        <div class="card-body">
            <div class="row align-items-center m-b-0">
                <div class="col">
                    <h6 class="m-b-5 text-white">{% trans %}title_document_archived{% endtrans %}</h6>
                </div>
                <div class="col-auto">
                  <i class="fas fa-archive text-white"></i>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% if shared is not defined %}
      {% if document.AllowShare %}
      <div class="card prod-p-card bg-danger background-pattern-white">
          <div class="card-body">
              <div class="row align-items-center m-b-0">
                  <div class="col">
                      <h6 class="m-b-5 text-white">{% trans %}title_document_shared{% endtrans %}</h6>
                  </div>
                  <div class="col-auto">
                    <i class="fas fa-exclamation-triangle text-white"></i>
                  </div>
              </div>
          </div>
      </div>
      {% endif %}
    {% endif %}


    <div class="document-container p-2 mt-2">

      <div class="row align-items-center">
        <div class="col-12 col-xl-3">
          <img src="{{ asset(groupLogo) }}" alt="{{document.mainGroup.shortname}}" class="img-fluid document-group-logo">
        </div>
        <div class="col">
          <h1 style="color:beige;">{{document.mainGroup.name}}</h1>
          <h2 style="color:beige;">{{ ('documentType_' ~ document.classShort)|trans }} #{{ document.getId }} : {{ document.getTitle }}</h2>
        </div>      
      </div>
      <hr>
      <div class="row p-2">
        <div class="col-12">
          {% include 'document/types/' ~ document.classShort ~ '.html.twig' with {'document': document} %}
        </div>
      </div>
      <hr>
      <div class="row mb-2">
        <div class="col-12 col-md-6">
          {% if shared is not defined and history |length > 1 %}
          <p>{% trans %}title_document_edited{% endtrans %} {{ history |length -1 }} {% trans %}since_its_creation{% endtrans %}. <a href="{{path('document_history', {'id': document.id})}}">{% trans %}button_view_history{% endtrans %}</a></p>
          {% endif %}
        </div>
        <div class="col-12 col-md-6">
          {{ document.creator.fullname }}, {% trans %}for{% endtrans %} {{ document.mainGroup.name }} <br>{% trans %}title_created_at{% endtrans %} {{ document.createdAt|date('_datetime.format'|trans) }}
          {% if shared is not defined %}<span class="float-end">{% include '_cells/documentActions.html.twig' with {'document': document} %}</span> {% endif %}
        </div>
      </div>

    </div>

    <div class="row mt-5">
      <div class="col-12">
        <h3>{% trans %}title_comments{% endtrans %} {% if shared is not defined %}<a href="#addcomment"><span class="badge rounded-pill bg-success"><i class="fa fa-plus"></i> {% trans %}button_add_comment{% endtrans %}</span></a>{% endif %}</h3><hr>
        
  
        <ul class="timeline">
          {% for c in document.comments %}
          <li>
            {{ c.creator.fullname }} {{c.creator.mainGroup ? c.creator.mainGroup.shortname : 'No Group'}}, {% trans %}title_created_at{% endtrans %} {{ c.createdAt|date('_datetime.format'|trans) }}
            <hr>            
            {{ c.content | raw }}
            <span class="float-end">{% if shared is not defined %}{% include '_cells/commentActions.html.twig' with {'comment': c} %}{% endif %}</span>
          </li>
          {% endfor %}
        </ul>     
      </div>
      {% if shared is not defined %}
      <div class="col-12" id="addcomment">
        <h3>{% trans %}title_comment_add{% endtrans %}</h3><hr>
        {{ form(formComment) }}
      </div>
      {% endif %}
    </div>

  </div>
  <div class="col-lg-4 col-xs-12">
    {% if document.directory is defined and document.directory is not null %}
      <h3>{% trans %}title_directory_linked{% endtrans %}</h3><hr>
      {% include '_cells/directoryCard.html.twig' with {'directory': document.directory} %}          
    {% endif %}
      
    {% if document.user is defined and document.user is not null %}
      <h3>{% trans %}title_user_linked{% endtrans %}</h3><hr>
      {% include '_cells/userInformations.html.twig' with {'user': document.user} %}         
    {% endif %}
  </div>
</div>
{% endblock %}